Add unit tests for org.antlr.v4.misc.CharSupport
Diffblue-benchmarks/Antlr-antlr4 pull request #1
Opened 2019-06-04 08:37 UTC by Braavos96

I've analysed your codebase and noticed that `org.antlr.v4.misc.CharSupport` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

2019-06-04 14:42 UTC, petersear requested changes

2019-06-04 14:42 UTC, petersear commented on tool/pom.xml
> -	</dependencies>
It's not obvious at first why the line containing `</dependencies>` is in the diffs but I can see that `<dependencies>` is indented with a `tab` whereas `</dependencies>` is indented using spaces so presumably that has changed from `tab`'s.

2019-06-04 14:42 UTC, petersear commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> + * Copyright (c) 2012-2017 The ANTLR Project. All rights reserved.
I'm not sure if we update copyright dates but, if so, `2017` should be replaced with `2019`.

2019-06-04 14:42 UTC, petersear commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
Why the blank line?

2019-06-04 14:42 UTC, petersear commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
Why the blank line?

2019-06-04 14:42 UTC, petersear commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
Why the blank line?

2019-06-04 14:58 UTC, Braavos96 commented on tool/pom.xml
> -	</dependencies>
Done

2019-06-04 14:58 UTC, Braavos96 commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> + * Copyright (c) 2012-2017 The ANTLR Project. All rights reserved.
Done

2019-06-04 14:59 UTC, Braavos96 commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
They are different switch cases in the same method

2019-06-04 14:59 UTC, Braavos96 commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
They are different switch cases in the same method

2019-06-04 14:59 UTC, Braavos96 commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
They are different switch cases in the same method

2019-06-04 14:59 UTC, Braavos96 commented on tool/test/java/org/antlr/v4/misc/CharSupportTest.java
> +
They are different switch cases in the same method

2019-06-04 15:52 UTC, freddytuxworth approved these changes

2019-06-05 06:33 UTC, petersear approved these changes

2019-06-06 09:46 UTC, paulkennethkent commented
As you are adding jUnit do you need surefire as well?

2019-06-07 10:10 UTC, Braavos96 commented
> As you are adding jUnit do you need surefire as well?

Move the tests to the test package. Junit was already there in the pom file

2019-06-07 15:25 UTC, paulkennethkent approved these changes

2019-07-11 08:48 UTC, closed without merging